### ISSUE TITLE
Issues installing plugin in Android

### ISSUE THREAD

**Issue by Jelmeaux** [jfpsf/flurry-phonegap-plugin#18]
Hi (again),

This time i've got a real problem :)

I've installed the plugin with CLI, got an error for the missing files (as expected), downloaded the necessary files from Flurry, put these in the correct folders (and renamed them), re-ran the install command with CLI so everything was copied nicely. So far so Good!

My config.xml file didn't get updated automatically. I've seen this before, and have implemented the lines needed from plugin.xml from the repository in my config.xml
Yet again, so far so good :)

But now i've run into a problem. In Eclipse i use for testing the android versions of the app, i get an error:
"The declared package co.themobilefirm.FlurryPlugin does not match the expected package co.themobilefirm.plugins"

The folders that were created when installing the plugin are src/co/themobilefirm/plugins/ with the Flurry.java file in there (and this file throws the error)
The public class created in this file is named Flurry, not FlurryPlugin.

In the config.xml file the plugin is defined as 

```
<feature name="FlurryPlugin">
        <param name="android-package" value="co.themobilefirm.FlurryPlugin" />
    </feature>
```

And in the plugin JS itself, the plugin is defined as 

```
cordova.define("co.themobilefirm.FlurryPlugin.FlurryPlugin", function(require, exports, module) {
```

I think there is a problem with the consistency of the naming of the plugin, but i do not have the required knowledge to fix this myself.

Any help is greatly appreciated.

ps: On iOS everything seems to work like a charm.

**Comment by orenku** [comment]
Patrick, 
Was this ever fixed in the repo?
I am seeing the same exception:
java.lang.ClassNotFoundException: com.phonegap.plugins.flurry
   at java.lang.Class.classForName(Native Method)
   at java.lang.Class.forName(Class.java:251)
   at java.lang.Class.forName(Class.java:216)
   at org.apache.cordova.PluginEntry.getClassByName(PluginEntry.java:117)
   at org.apache.cordova.PluginEntry.createPlugin(PluginEntry.java:93)

I am stuck with it for almost a day ;-)

Can someone help me here?

**Comment by jfpsf** [comment]
I will fix it this weekend

On Thu, Feb 26, 2015 at 8:40 AM, orenku <notifications@github.com> wrote:

> Patrick,
> Was this ever fixed in the repo?
> I am seeing the same exception:
> java.lang.ClassNotFoundException: com.phonegap.plugins.flurry
> at java.lang.Class.classForName(Native Method)
> at java.lang.Class.forName(Class.java:251)
> at java.lang.Class.forName(Class.java:216)
> at org.apache.cordova.PluginEntry.getClassByName(PluginEntry.java:117)
> at org.apache.cordova.PluginEntry.createPlugin(PluginEntry.java:93)
>
> I am stuck with it for almost a day ;-)
>
> Can someone help me here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfpsf/flurry-phonegap-plugin/issues/18#issuecomment-76179171>
> .
>



-- 
+++++++++++++++++++++++++++++++++++
John Potter
(415) 846-8021
+++++++++++++++++++++++++++++++++++

**Comment by orenku** [comment]
Thx,. 
I think I found the source of the problem in the plugin.xml: Need to add the name of the class to the value string, so it should be:
		<config-file target="res/xml/config.xml" parent="/*">
			<feature name="FlurryPlugin">
				<param name="android-package" value="com.phonegap.plugins.Flurry.Flurry" />
			</feature>
		</config-file>
I also used the latest Flurry version (>5), so the implementation had to be changed. Some new API needed to be added like init
If you're interested I can share with you my changes,

**Comment by jfpsf** [comment]
That would be great

On Thu, Feb 26, 2015 at 5:10 PM, orenku <notifications@github.com> wrote:

> Thx,.
> I think I found the source of the problem in the plugin.xml: Need to add
> the name of the class to the value string, so it should be:
>
>
>
>
>
> I also used the latest Flurry version (>5), so the implementation had to
> be changed. Some new API needed to be added like init
> If you're interested I can share with you my changes,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfpsf/flurry-phonegap-plugin/issues/18#issuecomment-76285360>
> .
>



-- 
+++++++++++++++++++++++++++++++++++
John Potter
(415) 846-8021
+++++++++++++++++++++++++++++++++++
