### ISSUE TITLE
How do you use this plugin?

### ISSUE THREAD

**Issue by FabioKB** [jfpsf/flurry-phonegap-plugin#19]
Sure I've read the README, installed with cordova, downloaded libs etc. but running Flurry.startSession('123xxx') seems to just crash my app/js.

Any more detailed instructions, maybe just the first 3 lines of code to get us started?

Debugging on Phonegap is tricky at the best of times.

P.S. Running Android.
Thanks!

**Comment by steiljes** [comment]
I haven't had much luck with this plugin :(

It works only if I add the session key in native code but then what would be the use for this plugin :)

I'm trying to make it work from my JS file and it's just not working

**Comment by shortnoticeapp** [comment]
When I do     console.log(window.plugins.flurry); I am getting 'undefined'. 

Any ideas? I have followed all of the steps and I'm struggling
