### ISSUE TITLE
Sessions not working in iOS

### ISSUE THREAD

**Issue by jproby** [jfpsf/flurry-phonegap-plugin#26]
More a question than an issue:
I am using the plugin with ionic/cordova 3.5 and after adding onStartSession etc. to my main class Android sessions are now recorded.
But iOS are not.
- How to modify my iOS code to enable session recording
- is it possible to record events without sessions (I understand this is strange) ?

Thank you for your help.

**Comment by joshbuchea** [comment]
In case I'm the only one who wasn't exactly sure how to "setSessionReportsOnCloseEnabled and setSessionReportsOnPauseEnabled to log the session", it can be accomplished like so:

```javascript
window.plugins.flurry.setSessionReportsOnCloseEnabled(true);
window.plugins.flurry.setSessionReportsOnPauseEnabled(true);
```
