### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by jasonhealy** [jfpsf/flurry-phonegap-plugin#27]
Hi, It's not very clear in the docs how to use the plugin. Could you do a step by step?

I followed the steps to install the IOS SDK here:
http://support.flurry.com/?title=Analytics/GettingStarted

It says to modify the AppDelegeate.m file and call the start session. Do I still need to start session from my JS app? And where are the docs for event tracking via js?

**Comment by joshbuchea** [comment]
Don't forgot to also "setSessionReportsOnCloseEnabled and setSessionReportsOnPauseEnabled to log the session", it can be accomplished after calling startSession() like so:

```javascript
window.plugins.flurry.setSessionReportsOnCloseEnabled(true);
window.plugins.flurry.setSessionReportsOnPauseEnabled(true);
```

**Comment by joshbuchea** [comment]
A simple example for iOS:

````javascript
if (window.plugins && window.plugins.flurry) {
  window.plugins.flurry.startSession('YOURAPIKEYHERE', function() {
    console.log('Flurry Success!');
    window.plugins.flurry.setSessionReportsOnCloseEnabled(true); // iOS only
    window.plugins.flurry.setSessionReportsOnPauseEnabled(true); // iOS only
  }, function() {
    alert('Flurry Error!');
  });
}
````

**Comment by iamaro** [comment]
@joshbuchea i'm using the exact example you've provided in your last comment, but nothing is showing up in the Flurry dashboard after around 12 hours.

All the code seems to be executing just fine, so I'm not sure what the issue could be.

Any ideas?
