### ISSUE TITLE
Plugin not working on android

### ISSUE THREAD

**Issue by UsmanAli-10p** [jfpsf/flurry-phonegap-plugin#30]
Hi, 
I added the plugin to my phone gap app via CLI. Its working flawlessly on iOS but when I run it on android I don't get success or failure callbacks and no events or sessions are being logged on flurry. Checked log cat and found this:

11-20 10:48:38.815: W/System.err(12645): java.lang.ClassNotFoundException: com.phonegap.plugins.Flurry
11-20 10:48:38.815: W/System.err(12645):    at java.lang.Class.classForName(Native Method)
11-20 10:48:38.815: W/System.err(12645):    at java.lang.Class.forName(Class.java:251)
11-20 10:48:38.815: W/System.err(12645):    at java.lang.Class.forName(Class.java:216)
11-20 10:48:38.815: W/System.err(12645):    at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:345)
11-20 10:48:38.815: W/System.err(12645):    at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:189)
11-20 10:48:38.815: W/System.err(12645):    at org.apache.cordova.PluginManager.exec(PluginManager.java:137)
11-20 10:48:38.815: W/System.err(12645):    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
11-20 10:48:38.815: W/System.err(12645):    at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:40)
11-20 10:48:38.815: W/System.err(12645):    at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
11-20 10:48:38.815: W/System.err(12645):    at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
11-20 10:48:38.815: W/System.err(12645):    at android.os.Handler.dispatchMessage(Handler.java:102)
11-20 10:48:38.815: W/System.err(12645):    at android.os.Looper.loop(Looper.java:136)
11-20 10:48:38.815: W/System.err(12645):    at android.os.HandlerThread.run(HandlerThread.java:61)
11-20 10:48:38.815: W/System.err(12645): Caused by: java.lang.NoClassDefFoundError: com/phonegap/plugins/Flurry
11-20 10:48:38.825: W/System.err(12645):    ... 13 more
11-20 10:48:38.825: W/System.err(12645): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.phonegap.plugins.Flurry" on path: DexPathList[[zip file "/data/app/com.analytics.integration-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.analytics.integration-1, /vendor/lib, /system/lib]]
11-20 10:48:38.825: W/System.err(12645):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-20 10:48:38.825: W/System.err(12645):    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
11-20 10:48:38.825: W/System.err(12645):    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
11-20 10:48:38.825: W/System.err(12645):    ... 13 more
11-20 10:48:38.825: I/System.out(12645): Error adding plugin com.phonegap.plugins.Flurry.
11-20 10:48:38.825: W/System.err(12645): java.lang.NullPointerException
11-20 10:48:38.825: W/System.err(12645):    at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:191)
11-20 10:48:38.825: W/System.err(12645):    at org.apache.cordova.PluginManager.exec(PluginManager.java:137)
11-20 10:48:38.825: W/System.err(12645):    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
11-20 10:48:38.825: W/System.err(12645):    at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:40)
11-20 10:48:38.825: W/System.err(12645):    at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
11-20 10:48:38.825: W/System.err(12645):    at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
11-20 10:48:38.825: W/System.err(12645):    at android.os.Handler.dispatchMessage(Handler.java:102)
11-20 10:48:38.825: W/System.err(12645):    at android.os.Looper.loop(Looper.java:136)
11-20 10:48:38.825: W/System.err(12645):    at android.os.HandlerThread.run(HandlerThread.java:61)

I've followed all the instructions to the letter. I've removed my android platforms as well as the plugin and added them back again but still no luck. Please help!

**Comment by thomasMary** [comment]
hi @MrMaanAli 
I've the same issue, I tried to rm/add the plugin, but i'm still have this error:
   java.lang.ClassNotFoundException: com.phonegap.plugins.Flurry
And i dont really want to mess your plugin, do you have any idea where that could come from and if it's possible to fix it ?
