### ISSUE TITLE
Support for Android's Flurry Analytics SDK 5.0.0 ?

### ISSUE THREAD

**Issue by olexme** [jfpsf/flurry-phonegap-plugin#32]
Is mentioned version supported by current version of the plugin ?
I've downloaded newest version of Android's Flurry Analytics - SDK 5.0.0, copied FlurryAnalytics-5.0.0.jar (NOT FlurryAgent-*.jar like described in Usage/Installation)  to platforms/andorid/libs and nothing works.
I mean flurry plugin seems to be available, but neither succes nor error function is called when tried this

  flurry.startSession("XXXX", function success (okMsg) {
    console.log("flurry ok startSession:" + okMsg);
  }, function error (errMsg) {
    console.log("!ERR flurry startSession:" + errMsg);
  });

**Comment by koraybalci** [comment]
As you can also see in Flurry.java source of plugin, startSession relies on a FlurryAgent global object and calls onStartSession. If it fails somehow, it must return a message in error callback. If no errors, again success callback should have been called.

I tested the plugin with Flurry lib version 4.2.0 but I doubt this is an issue of lib versions, sounds like your plugin is not installed properly or you are looking at wrong logcat log somehow. 

Ops, just saw that your callback functions are not correctly defined, that's not how you define functions in javascript (afaik), you should not put the name of the function.

**Comment by olexme** [comment]
Callback functions are ok, they are just named functions (in oposite to anonymous that you suggest). Anyway I tried with anonymous functions and it doesn't help. I suspect that it might be SDK version issue, however version 5.0 compiles without any error. The problem is that older version of SDK isn't available for download on flurry.com anymore, or I don't know how to get it.

**Comment by koraybalci** [comment]
Looks like they have moved to yahoo, https://developer.yahoo.com/flurry/docs/analytics/gettingstarted/android/#get-started-with-android-5-0-add-calls-to-init-onstartsession-and-onendsession

The new 5.0 seem to have an extra "init" function, in short, they have changed the api. I could try to upgrade the plugin (skim the new api, fork and patch the plugin) but I am swamped at work with other things these weeks. You could either upgrade the plugin yourself or try to find the old jar.
