### ISSUE TITLE
log events with params not working

### ISSUE THREAD

**Issue by samrat-shekhar** [jfpsf/flurry-phonegap-plugin#40]
var quizParams = {
                quizName: String(bbGame.gameName),
                noOfQuestions: String(this.questions.length),
                correctNumberOfAnswers: String(correctAnswers),
                finalScore: String(scp)
                }
                window.plugins.flurry.logEventWithParameters('quiz end', quizParams, function() {
                                               console.log('quiz!');
                                               }, function(err) {
                                               console.error(['WTF?', err]);
                                               });

Above is the code snippet which gives the following console log:

2015-06-24 14:24:29.775 ImpartIQ[9483:192727] Event Parameters: {
    correctNumberOfAnswers = 6;
    finalScore = 30;
    noOfQuestions = 20;
    quizName = spon;
}
2015-06-24 14:24:29.799 ImpartIQ[9483:172254] quiz!

Its been more than 24 hours, but the same doesn't reflect in Flurry dashboard. Btw, Cordova v5.0, iOS app, Xcode v6.3

Could you please point out erroneous implementation if any? Thanks in advance!

**Comment by iamaro** [comment]
Did you ever get this working? I, too, am having issues with logged events not showing up in flurry.

**Comment by samrat-shekhar** [comment]
Hey @iamaro 
If you're still facing issue with logging events, contact the wonderful folks at flurry. I'm sure they'll sort things out for you, just like they did for me.
