### ISSUE TITLE
Does this plugin still work?

### ISSUE THREAD

**Issue by iamaro** [jfpsf/flurry-phonegap-plugin#41]
I have the plugin installed and everything on iOS

and am able to start session without any errors and run the following two commands

window.plugins.flurry.setSessionReportsOnCloseEnabled(true);
window.plugins.flurry.setSessionReportsOnPauseEnabled(true);

For some reason, though, my flurry analytics dashboard is not updating. It's been 12 hours now since starting to test -- does it take longer than this?

Thanks,
Clay

**Comment by samrat-shekhar** [comment]
can't say why its not working but you can enable debug logging and checkout if the session is actually being logged as follows:
if (window.plugins && window.plugins.flurry) {
                    window.plugins.flurry.startSession("TSNxxxxxxxxxxxxxxB9B", function () {
                        console.log('Flurry Success!');
                        window.plugins.flurry.setSessionReportsOnCloseEnabled(true); // iOS only
                        window.plugins.flurry.setSessionReportsOnPauseEnabled(true); // iOS only
                                                       window.plugins.flurry.setEventLoggingEnabled(true);
                                                       window.plugins.flurry.setDebugLogEnabled(true);
                    }, function () {
                        alert('Flurry Error!');
                    });
                }

Also the session won't be logged until the app goes in the background, (i.e stopping the application from xcode wont log the event).

**Comment by iamaro** [comment]
So I think things appear to be being logged according to the logs

I'm seeing a http request being sent to data.flurry.com

and some lines like FlurrySession: Add session with startTime[2015-07-05 06:27:08 +0000] to saved sessions

But still nothing in the flurry dashboard. Is there any way this could just be a super long delay?

Could this be related to not having an app store ID yet?

**Comment by iamaro** [comment]
Data just started showing up ( and appears to include everything from today ), so maybe there's just a super long delay the first time or something.

Either way, thanks for the help!
