### ISSUE TITLE
Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture

### ISSUE THREAD

**Issue by NishantSolanki** [jfpsf/flurry-phonegap-plugin#44]
I am getting this error...

Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture

While building IOS app from adobe build

I put below code to my config.xml

<gap:plugin name="com.flurry.plugins.flurry" version="3.4.8" />

Please help

**Comment by NishantSolanki** [comment]
Please someone repond,, have anyone faced this issue before??
How to solve it

**Comment by jfpsf** [comment]
This is a new issue that we have not seen before. It will take some
research.

On Mon, Aug 17, 2015 at 12:21 AM, NishantSolanki <notifications@github.com>
wrote:

> Please someone repond,, have anyone faced this issue before??
> How to solve it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfpsf/flurry-phonegap-plugin/issues/44#issuecomment-131704096>
> .
>



-- 
+++++++++++++++++++++++++++++++++++
John Potter
(415) 846-8021
+++++++++++++++++++++++++++++++++++

**Comment by NishantSolanki** [comment]
Ok no problem, I am using your plugin from below adobe plugin lists

https://build.phonegap.com/plugins/1876

and using this code in my config.xml file

<gap:plugin name="com.flurry.plugins.flurry" version="3.4.8" />

**Comment by bobisum** [comment]
Hi there,

I have the same issue. Any info on that?

Thanks.

**Comment by NishantSolanki** [comment]
Yes, you have to install the plugin using your pc's command line interface.
and do use the same for generating an apk or ipa build.
If you are using adobe to generate the apk/ipa then it will give you the same error.

Let me know if any other help needed.

**Comment by bobisum** [comment]
Thanks, can you contact me on my email? I've made it public on my acc. Will delete this comment after that to keep the spam out.

**Comment by micsun-al** [comment]
Changing that line to the following "worked" for me.  Other issues arose though...

`<plugin name="com.flurry.plugins.flurry" source="npm" />`
