### ISSUE TITLE
Can not build using PhoneGap Build

### ISSUE THREAD

**Issue by zigzag-way** [jfpsf/flurry-phonegap-plugin#47]
If I add the plugin to my config.xml online PhoneGap Build stops building it for iOS (((

**Comment by micsun-al** [comment]
I can't get this to work using PhoneGap Build also.
I asked in a few forums for help, and here's a link to the threads in case someone answers there...

- https://forums.adobe.com/message/8991327#8991327
- https://forums.developer.yahoo.net/discussion/9374/adobe-phonegap-build
