### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by ChrisDevinePimss** [jfpsf/flurry-phonegap-plugin#48]
First Issue:
just installed the plugin and i was following the instructions and got to the point where i need to copy "FlurryAgent-_.jar". This is a problem for me as my android sdk does not contain a FlurryAgent-_.jar only a "FlurryAnalytics-6.1.0.jar". Is this going to be a problem or does the documentation just need updating. Which brings me to the second issue

Second Issue:

 i cant rebuild... I am getting output below 

Install start for "com.phonegap.plugins.Flurry" on android.
1>  Beginning processing of action stack for android project...
1>  Parsing android project files...
1>  Installing Android library: com.google.android.gms:play-services-plus:+
1>  Error during processing of action! Attempting to revert...
1>  Failed to install 'com.phonegap.plugins.Flurry':TypeError Uh oh!
1>  Arguments to path.resolve must be strings
1>      at Object.win32.resolve (path.js:146:13)
1>      at module.exports.framework.install (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35)
1>      at Object.ActionStack.process (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25)
1>      at handleInstall (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:575:20)
1>      at C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:335:28
1>      at _fulfilled (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:787:54)
1>      at self.promiseDispatch.done (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:816:30)
1>      at Promise.promise.promiseDispatch (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:749:13)
1>      at C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:509:49
1>      at flush (C:\Users\ChrisDevine\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:108:17)
1>  TypeError: Uh oh!
1>  Arguments to path.resolve must be strings
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by berndartmueller** [comment]
Same problem here

**Comment by jfpsf** [comment]
Guys, I'll take a look at this as soon as I can, but won't be until this weekend.

**Comment by LilDevine89** [comment]
Thanks for the quick response jfpsf, looking forward to giving it a try Monday. Don't work to hard on the weekend

**Comment by LilDevine89** [comment]
@berndartmueller Managed to get it to build by doing this:


1. Updated cordova with the new MS Cordova Tools update 3
2. Updated the project to use Cordova 5.1.1
3. Download this plugin to local and installed it from the downloaded file.
4. Changed the name of android SDK from FlurryAnalytics-6.1.0.jar to FlurryAgent-6.1.0.jar
5. Placed the needed files in the plugins > com.phonegap.plugins.Flurry > src > (then android or ios depending on the file. So fluryAgent.jar went in android)
6. Added the following lines to the plugins > com.phonegap.plugins.Flurry > plugin.xml 
 under "<platform name="ios">" i added
"<source-file src="src/ios/libFlurry_7.2.1.a" framework="true" />"

under "<platform name="android">" i added
"<source-file src="src/android/FlurryAgent-6.1.0.jar" target-dir="libs" />"

Now the rebuild all went well but not tested functionality yet. I will report back if it works, but now you have a good starting point

**Comment by jfpsf** [comment]
If it works, you can always submit the altered files. I'll merge them in, and give you credit

**Comment by LilDevine89** [comment]
How do i submit the altered files? (am a tfs kind of guy ha)

**Comment by jfpsf** [comment]
You can just attach them to this issue, and I'll handle the actual integration

**Comment by LilDevine89** [comment]
problem uploading to the issue 

http://www.filedropper.com/update_9

**Comment by jfpsf** [comment]
Thanks a lot.  I'll do the merge this weekend.
