### ISSUE TITLE
Flurry integration in phone-gap (android) project causing issues

### ISSUE THREAD

**Issue by riksof-abdulrauf** [jfpsf/flurry-phonegap-plugin#49]
Flurry integration in phone-gap (android) project causing issues
Please read the question asked on stack-overflow.

http://stackoverflow.com/questions/33084633/flurry-integration-in-phone-gap-project-causing-issues

thank in advance

**Comment by jfpsf** [comment]
Answered on StackOverflow

**Comment by riksof-abdulrauf** [comment]
@jfpsf : Did it fixed ? I am still facing issue
