### ISSUE TITLE
Flurry integration in phone-gap (android) project causing issues

### ISSUE THREAD

**Issue by riksof-abdulrauf** [jfpsf/flurry-phonegap-plugin#50]
I am integrating flurry with the help of
https://github.com/jfpsf/flurry-phonegap-plugin

I manually copied the FlurryAnalytics-6.0.0.jar file
<img src="http://i.stack.imgur.com/txoFd.png">

I have installed following plugins <br/>
<img src="http://i.stack.imgur.com/sfkVe.png">

but when I run the command for creating build

```
cordova run
```

It gives me following errors

```
    $ cordova run
Running command: /Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/cordova/run 
ANDROID_HOME=/usr/local/Cellar/android-sdk/24.3.4
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home
WARNING : No target specified, deploying to device '192.168.56.101:5555'.
Running: /Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/gradlew cdvBuildDebug -b /Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/build.gradle -PcdvBuildArch=x86 -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:22.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
         file:/usr/local/Cellar/android-sdk/24.3.4/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
         file:/usr/local/Cellar/android-sdk/24.3.4/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
     Required by:
         :android:unspecified > com.google.android.gms:play-services-plus:8.1.0 > com.google.android.gms:play-services-base:8.1.0 > com.google.android.gms:play-services-basement:8.1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.232 secs

/Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/build.gradle,-PcdvBuildArch=x86,-Dorg.gradle.daemon=true
ERROR running one or more of the platforms: Error: /Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/cordova/run: Command failed with exit code 1
You may not have the required environment or OS to run this project
```

Please let me know what I have to do for it, build works fine before flurry plugin integration.

**Comment by jfpsf** [comment]
Still working on it.

**Comment by jfpsf** [comment]
Try now with new files

**Comment by riksof-abdulrauf** [comment]
Still not working,

I removed android platform and all plugins, 
then re-install

       cordova platform add android

       cordova plugin add cordova-plugin-statusbar
       cordova plugin add cordova-plugin-dialogs
       cordova plugin add cordova-plugin-network-information
       cordova plugin add cordova-plugin-splashscreen

       cordova plugin add https://github.com/jfpsf/flurry-phonegap-plugin.git  

Copied FlurryAgent.jar into the 'plugin/com.phonegap.plugins.Flurry/src/android' folder
but still getting error

        rufiMacMini1:Chatbudi-client rauf$ cordova run
Running command: /Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/cordova/run 
ANDROID_HOME=/usr/local/Cellar/android-sdk/24.3.4
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home
WARNING : No target specified, deploying to device '192.168.56.101:5555'.
Running: /Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/gradlew cdvBuildDebug -b /Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/build.gradle -PcdvBuildArch=x86 -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:22.2.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
         file:/usr/local/Cellar/android-sdk/24.3.4/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.pom
         file:/usr/local/Cellar/android-sdk/24.3.4/extras/google/m2repository/com/android/support/support-v4/22.2.0/support-v4-22.2.0.aar
     Required by:
         :android:unspecified > com.google.android.gms:play-services-plus:8.1.0 > com.google.android.gms:play-services-base:8.1.0 > com.google.android.gms:play-services-basement:8.1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 41.265 secs

/Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/build.gradle,-PcdvBuildArch=x86,-Dorg.gradle.daemon=true
ERROR running one or more of the platforms: Error: /Users/rauf/Documents/Chatbudi/Chatbudi-client/platforms/android/cordova/run: Command failed with exit code 1
You may not have the required environment or OS to run this project
rufiMacMini1:Chatbudi-client rauf$
