### ISSUE TITLE
setSessionReportsOnCloseEnabled to use 'Yes' or true?

### ISSUE THREAD

**Issue by gsccheng** [jfpsf/flurry-phonegap-plugin#53]
In the examples, the methods `setSessionReportsOnCloseEnabled` and `setSessionReportsOnPauseEnabled` uses a `true` argument. 

However, in the comments for those methods in `flurryPlugin.js` it says to use `'Yes'` or `'No'`. Which is it? It looks like it doesn't matter because of your `bool2ObjC` helper function? 

I'm asking because I'm not getting all my parameters (particularly the audience (i.e. age, userId) and error logs) showing up in my Flurry dashboard and I want to make sure I'm setting up my session correctly.

Thanks.

**Comment by jfpsf** [comment]
It used to be yes and no, now it's true/false. We just never updated the
comments

On Tue, Nov 10, 2015 at 9:01 AM, Gabriel Cheng <notifications@github.com>
wrote:

> In the examples, the methods setSessionReportsOnCloseEnabled and
> setSessionReportsOnPauseEnabled uses a true argument.
>
> However, in the comments for those methods in flurryPlugin.js it says to
> use 'Yes' or 'No'. Which is it? I'm asking because I'm not getting all my
> parameters (particularly the audience (i.e. age, userId) and error logs)
> showing up in my Flurry dashboard and I want to make sure I'm setting up my
> session correctly.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfpsf/flurry-phonegap-plugin/issues/53>.
>



-- 
+++++++++++++++++++++++++++++++++++
John Potter
(415) 846-8021
+++++++++++++++++++++++++++++++++++

**Comment by gsccheng** [comment]
Okay, thanks.

**Comment by gsccheng** [comment]
Okay, thanks.

**Comment by gsccheng** [comment]
Are the argument types still correct? So userID should still be a string and age must still be an integer?

```
  // userID must be a string
  Flurry.prototype.setUserID = function(userID, successCallback, failureCallback) {
    return cordova.exec( successCallback, failureCallback, 'FlurryPlugin', 'setUserID', [userID]);
  };
```
```
  // age must be an integer
  Flurry.prototype.setAge = function(age, successCallback, failureCallback) {
    return cordova.exec( successCallback, failureCallback, 'FlurryPlugin', 'setAge', [age]);
  };
```
