### ISSUE TITLE
Flurry Phonegap Android Integration Problem

### ISSUE THREAD

**Issue by riksof-arqam** [jfpsf/flurry-phonegap-plugin#55]
I have followed all the steps described at
https://github.com/jfpsf/flurry-phonegap-plugin
but when I run my app on android, after splash screen there is a white screen.
Kindly resolve this problem or guide me if I am mistaken.

**Comment by jfpsf** [comment]
What makes you think it is the plugin causing this behavior?

On Thu, Nov 12, 2015 at 5:47 AM, riksof-arqam <notifications@github.com>
wrote:

> I have followed all the steps described at
> https://github.com/jfpsf/flurry-phonegap-plugin
> but when I run my app on android, after splash screen there is a white
> screen.
> Kindly resolve this problem or guide me if I am mistaken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfpsf/flurry-phonegap-plugin/issues/55>.
>



-- 
+++++++++++++++++++++++++++++++++++
John Potter
(415) 846-8021
+++++++++++++++++++++++++++++++++++

**Comment by riksof-arqam** [comment]
When I run the app, everything works fine. But at this line
            app.flurry = window.plugins.flurry;
app shows white screen.

Below is the code snippet:
var app = {
platforms: {
android: 'android',
ios: 'ios'
},
platform: 'android',
/**
* Global Variable
* calls limit for all AJAX Requests
*/
AJAX_CALLS_LIMIT: 3,
AJAX_CALLS_TIMEOUT: 15000,
AJAX_RETRY_TIMEOUT: 30000,//5 * 60000,
MESSAGES: {
NTERNET_ERROR: "There seems to be a problem with your network connection.
Please try again later."
}
flurry: null

app.flurry = window.plugins.flurry;

**Comment by shortnoticeapp** [comment]
I have the same issue. Was this ever resolved?
