### ISSUE TITLE
Can't build iOS cordova app

### ISSUE THREAD

**Issue by hhaider** [jfpsf/flurry-phonegap-plugin#58]
I've added libFlurry.a under /plugins/src/ios/libFlurry.a
I've added Security, CFNetwork, SystemConfiguration and libFlurry.a to build phases -> link binary with libraries

<img width="706" alt="screen shot 2017-02-13 at 4 25 16 pm" src="https://cloud.githubusercontent.com/assets/1668799/22904082/0b1a3260-f209-11e6-98a4-d57e3bc274df.png">

Getting this error when building with Cordova:
```Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SKPaymentQueue", referenced from:
      objc-class-ref in libFlurry.a(libFlurry.a-i386-master.o)
  "_OBJC_CLASS_$_SKProductsRequest", referenced from:
      objc-class-ref in libFlurry.a(libFlurry.a-i386-master.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by hhaider** [comment]
Fixed,
For some reason I had to add StoreKit.framework to the list of Link Binary with Libraries.
Project now compiles and builds, and the plugin works!

**Comment by jfpsf** [comment]
Great Thanks
