### ISSUE TITLE
Android logs sessions but doesn't log events

### ISSUE THREAD

**Issue by hhaider** [jfpsf/flurry-phonegap-plugin#59]
The iOS version of the app is working fine, records both sessions and events.
However, the android version of the app seems to only record sessions, when I go to Event Logs, it shows "No data to display".
Anyone experience this before?
Thanks

**Comment by ghost** [comment]
Hello, I don't seem to be recording event logs as well on Android. I invoke startSession on device ready with the proper API key and I receive the success callback. When I try to record an event with logEvent(), I again get the success callback, but nothing seems to be recording in my Flurry dashboard.

Here is my code :

on device ready:

       window.plugins.flurry.startSession(FLURRY_API_KEY, () => {
            console.log("session start success");
        }, () => {
            console.log("session start fail");
        });

when the play button is hit: 

        window.plugins.flurry.logEvent("play_hit", () => {
                        console.log("play event success");
                    }, () => {
                        console.log("play event failure");
                    })

Also, do these custom events automatically get displayed in the dashboard, or should I create an event there and match it with the namings in my cod? I couldn't get any info on that. 

Thanks in advance!

**Comment by ghost** [comment]
Just a quick update, I just saw that in the "Events Details" tab of my Flurry dashboard I now have the "play_hit" event listed. However, it seem that no metrics are being recorded. In the "Events Logs" tab I can select the game and the "play_hit" event, but it still says "There is no data to display". Will contact Flurry support to check this out.

**Comment by ghost** [comment]
Another update. My events are working correctly and are being displayed in the dashboard. Turns out the "Events Details" tab updates on a daily basis and the more detailed information in the "Events Logs" tab takes even a bit more time to generate and update, but as of now, everything is there.

**Comment by jfpsf** [comment]
This is a really common issue with Flurry.  We've had multiple issues that turned out to be this.
